# Generated by Django 5.2.4 on 2026-02-20 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('job_role', models.TextField(choices=[('python_dev', 'Python Developer'), ('data_analyst', 'Data Analyst'), ('frontend_dev', 'Frontend Developer'), ('backend_dev', 'backend Developer')], max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('matched_keywords', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
