# Generated by Django 5.2.4 on 2026-04-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resume_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
        migrations.AlterField(
            model_name='resume',
            name='job_role',
            field=models.TextField(choices=[('python_dev', 'Python Developer'), ('data_analyst', 'Data Analyst'), ('frontend_dev', 'Frontend Developer'), ('backend_dev', 'Backend Developer'), ('fullstack_dev', 'Full Stack Developer'), ('devops_engine', 'DevOps Engineer'), ('java_dev', 'Java Developer')], max_length=50),
        ),
    ]
